import com.google.gson.Gson;
import org.apache.commons.lang3.StringEscapeUtils;

/**
 * Created by jessesleep on 11/5/15.
 */
public class Q2Q3TweetStructure {
    public long id;
    public long userId;
    public int skewedTimestamp;
    public String censoredText;
    public int sentimentScore;
    public int impactScore;

    public Q2Q3TweetStructure(){}

    /**
     * Recover a TweetStructure from a json line generated by ETL phase 1
     * @param jsonLine
     */
    public Q2Q3TweetStructure(String jsonLine){
        Gson gson = new Gson();
        Q2Q3TweetStructure temp = gson.fromJson(jsonLine, this.getClass());
        this.id = temp.id;
        this.userId = temp.userId;
        this.skewedTimestamp = temp.skewedTimestamp;
        this.censoredText = temp.censoredText;
        this.sentimentScore = temp.sentimentScore;
        this.impactScore = temp.impactScore;
    }

    /**
     * Translate a TweetStructure into a json line
     * @return
     */
    public String toJsonLine(){
        Gson gson = new Gson();
        String json = gson.toJson(this);

        return json;
    }

    /**
     * Output in a csv format. Multi line....
     * @return
     */
    public String toEscapeString() {
        return id + "," + userId + "," + skewedTimestamp + "," +
                sentimentScore + "," + impactScore + "," +
                 StringEscapeUtils.escapeCsv(censoredText);
    }


}
