import com.google.gson.Gson;
import org.apache.commons.lang3.StringEscapeUtils;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.TimeZone;

/**
 * Created by omega on 10/24/15.
 */
public class TweetStructure {
    public long id;
    public long userId;
    public long timestamp;
    public String text;
    public int follwersCount;
    public ArrayList<String> hashtags;

    public TweetStructure(long id, long userId,
                          long timestamp, String censoredText,
                          Integer followersCount, ArrayList<String> hashtags) {
        this.id = id;
        this.userId = userId;
        this.timestamp = timestamp;
        this.text = censoredText;
        this.follwersCount = followersCount;
        this.hashtags = hashtags;
    }

    public TweetStructure() {
        hashtags = new ArrayList<String>();
    }

    /**
     * Recover a TweetStructure from a json line generated by ETL phase 1
     * @param jsonLine
     */
    public TweetStructure( String jsonLine ){
        Gson gson = new Gson();
        TweetStructure temp = gson.fromJson(jsonLine, this.getClass());
        this.id = temp.id;
        this.userId = temp.userId;
        this.timestamp = temp.timestamp;
        this.text = temp.text;
        this.follwersCount = temp.follwersCount;
        this.hashtags = temp.hashtags;
    }

    /**
     * Translate a TweetStructure into a json line
     * @return
     */
    public String toJsonLine(){
        Gson gson = new Gson();
        String json = gson.toJson(this);

        return json;
    }

    public String toEscapeString() {
        return id + "," + userId + "," + timestamp + "," +
                StringEscapeUtils.escapeCsv(text);
    }

    /**
     * For debug usage
     * @return
     */
    public String toString(){
        String res = "id: " + this.id + " userId: " + this.userId + " timestamp: " + timestamp +
                "\n\ttext: " + this.text +
                "\n\tfollowersCount: " + this.follwersCount +
                "\n\tHashtags: ";
        for( String tag : this.hashtags ){
            res += tag+",";
        }

        return res+"\n";
    }
}
